title: Data Journey
formspree_email_id: xnqlzldw
email: zguang.loh@gmail.com
description: Data Science Learning Blog
author: lzguangzl
baseurl: ""
url: "https://lzguangzl.github.io"

# Social Profiles
twitter_username: lzguangzl
github_username: lzguangzl
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

